---
config:
  theme: neo-dark
  layout: dagre
  look: classic
id: 49545e5e-a489-49cd-bf70-a0450f55a302
---
flowchart TB
    A(["Ask AI tutor"]) --> B{"AI tutor"}
    B --> C["tool"] & D["resource"] & E["prompt"]
    C --> F["classmaterial"] & G["problems"]
    D --> H["problems_list"] & I["shared_class_materials"]
    E --> J["problems_exercises"] & K["reviewing_chapter"]
    